controller_manager:
    ros__parameters:
      update_rate: 100
      use_sim_time: true

      diff_controller:
        type: diff_drive_controller/DiffDriveController

      position_controller:
        type: position_controllers/JointGroupPositionController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    base_frame_id: body

    wheel_separation: 0.4
    wheel_radius: 0.05449

    left_wheel_names: ['wheel_bl_joint', 'wheel_fl_joint']
    right_wheel_names: ['wheel_br_joint', 'wheel_fr_joint']

position_controller:
  ros__parameters:
    joints:
      - cam_joint
      - rotate_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity